### ISSUE TITLE
Log rotation

### ISSUE THREAD

**Issue by Echsecutor** [hyperledger/indy-node-container#68]
Currently logs are rotated but kept forever. Investigate how the indy node logging works (which python libs) and how to configure it.

**Comment by Echsecutor** [comment]
Also:

- limit docker logs
  - https://docs.docker.com/config/containers/logging/configure/
```
logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
```
- default log level?
  - https://github.com/hyperledger/indy-node-container/blob/main/run/etc_indy/indy_config.py
  - set to 1 and adapt run/README.md
